### ISSUE TITLE
All render WAVs are truncated and how to select 24 bit?

### ISSUE THREAD

**Issue by ValZapod** [VoidXH/Cavern#62] opened 2023-01-11 22:05 UTC
Even on latest pink noise commit it shows isTruncated and 16 bit:

![image](https://user-images.githubusercontent.com/31514790/211925252-49f07987-dcc1-4996-8d80-55e63b1e3736.png)

Ffmpeg produces good file just use ffmpeg -i cnahcna8.wav **-bitexact**  -c copy nfwaw1.wav

that will not have the LIST chunk. One time remuxing is enough. Files attached. The problem is two places, before and after:
Size: 73691172 (0x04647024) and Size: 73531452 (0x0462003C)
Size: 73531452 (0x0462003C) and Size: 73531392 (0x04620000)

[11.zip](https://github.com/VoidXH/Cavern/files/10396237/11.zip)

**Comment by ValZapod** [comment] 2023-01-11 22:35
This is not talking about ADM. ADMs are not truncated.

**Comment by VoidXH** [comment] 2023-01-11 23:23
Then I'll just zero pad or update the length in Dispose. For 24 bit, it will be a toggle somewhere, just not in the spotlight.

**Comment by ValZapod** [comment] 2023-01-12 00:06
>Then I'll just zero pad

Right, ADM has 3070464 samples, yet rendered WAV has only 3063808 samples... Why is that? Ha.

>For 24 bit, it will be a toggle somewhere, just not in the spotlight.

You can use same method used in iXML extraction or add another button there.

**Comment by VoidXH** [comment] 2023-01-12 07:50
Header sizes fixed in afa428d4bc43f151852eab474a0f6c0d2cafc890, the issue was not the incorrect length, but not adding WAVEFORMATEXTENSIBLE bytes to the file size. The length is taken from the input file.

24-bit forcing was added as a check box under Rendering in 98a4c5328531c3f26809c8184a252beea95d90de.

**Closed by VoidXH** 2023-01-12 07:50 UTC
Labels: bug

**Comment by ValZapod** [comment] 2023-01-12 08:09
Still truncated. You changed only first value from 0x24 byte to 0x3C byte. But what should have happened is to 0x00 and next byte to 0x62. Also there is a second change from 0x70 0x64 to 0x00 0x62.

**Comment by VoidXH** [comment] 2023-01-12 08:14
> Still truncated.

Please send a file that does this, I couldn't reproduce.

> BTW, I still do not get why render in smaller than ADM.

Because 24 bit is useless. It just takes more time and space for barely any extra information that's not even audible.

**Comment by ValZapod** [comment] 2023-01-12 08:19
I mean smaller is the number of samples.

Sample is this to 7.1.4:  https://drive.google.com/file/d/1L7hYPf4tdbSGpFhlt6w4CKSTSb6ULPlY/view

**Comment by VoidXH** [comment] 2023-01-12 08:20
> I mean smaller is the number of samples.

It runs until the source file is not over.

**Comment by ValZapod** [comment] 2023-01-12 08:21
Okay, each frame in EAC3 has 256 samples. I m talking about those samples.

**Comment by VoidXH** [comment] 2023-01-12 08:22
The file size you written is divisible with 256.

**Comment by ValZapod** [comment] 2023-01-12 08:28
Yes, the number of samples is devisible by 256, because you are supposed to use editlist of the container to remove start (usually just 256) and end (that may be smaller than 1 frame). I already mentioned that.

BTW, that new flag now created 16 bit ADM files. That is invalid AFAIK. ADM is only 24 bit.

**Comment by ValZapod** [comment] 2023-01-12 08:34
BTW, I checked and 24 bit is conpressed in TrueHD better than 16 bit in Dolby Media Encoder. So...

**Comment by ValZapod** [comment] 2023-01-12 08:42
I also checked and tried encoding from ADM directly... Same happens. Also when I encode ADM to ADM it adds another 10 channels.

**Comment by VoidXH** [comment] 2023-01-12 08:43
> BTW, that new flag now created 16 bit ADM files. That is invalid AFAIK. ADM is only 24 bit. But it does work in Media Encoder.

The standard does not mention bit depth, I've checked DACT before pushing. The 24-bit checkbox also applies for ADM.

> when I encode ADM to ADM it adds another 10 channels.

That's required by Dolby. If those 10 channels are not there, the file is not readable by Dolby plugins.

**Comment by ValZapod** [comment] 2023-01-12 08:48
>That's required by Dolby

Any reencode adds another 10 channels even if source is **Atmos ADM** that already has 10 beds...

>The standard does not mention bit depth

Yeah, it does work in Media Encoder...

**Comment by VoidXH** [comment] 2023-01-12 08:50
> Any reencode adds another 10 channels even if source is **Atmos ADM** that already has 10 beds...

Yes, that's a known issue.

**Comment by ValZapod** [comment] 2023-01-12 08:57
What are the sizes your compiled app reports? 
Is that the same as my 

>changed only first value from 0x24 byte to 0x3C byte.

?

**Comment by VoidXH** [comment] 2023-01-12 09:15
Yes, it's intended and correct. 0x3C is 60, 16 bytes of FMT content, 24 bytes of WAVEFORMATEX header content, and 20 bytes of overhead (tags, lengths).

**Comment by ValZapod** [comment] 2023-01-12 09:29
>0x3C is 60, 16 bytes of FMT content, 24 bytes of WAVEFORMATEX header content, and 20 bytes of overhead 

Actually it is part of 0x0464703C, global size parameter that is a 32 bit value. See before and after:

![image](https://user-images.githubusercontent.com/31514790/212029757-2c9c8fe3-49c7-4765-b3f4-28111c13a5d8.png)

**Comment by VoidXH** [comment] 2023-01-12 09:32
Oh, sorry, the 20 bytes are the total overhead, not just the FMT, and this 60 is added to the file size, see the commit. Namings are wrong, function is correct.

**Comment by ValZapod** [comment] 2023-01-12 09:38
Yes, but see it is supposed to be 0x0462**00**3C to be valid wav. And Raw datas HEADER is supposed to have size that is 0x04620000. 

![image](https://user-images.githubusercontent.com/31514790/212031503-0b4715d3-72ac-4699-ab77-385153b7287d.png)


>Besides this is not real truncation but incorrect metadata aka "duration".

I was wrong. ADM tracks are longer than render tracks in Audacity. That is the underlying bug. All that assymetric renderer and stuff...

**Comment by ValZapod** [comment] 2023-01-12 09:48
The truncation happens at the end, happens even when you render from Atmos ADM and 

![image](https://user-images.githubusercontent.com/31514790/212033807-98957df0-6258-4970-860d-ee927e0c7d20.png)

**Comment by VoidXH** [comment] 2023-01-13 01:37
Added protection for writing both more and less samples in afa428d4bc43f151852eab474a0f6c0d2cafc890.

**Comment by ValZapod** [comment] 2023-01-13 04:51
It is now all the same size. Very nice. Fixed :)

**Comment by VoidXH** [comment] 2023-01-13 07:52
Maybe this fixed #64 then. I need to check again.

**Comment by ValZapod** [comment] 2023-01-26 11:19
I propose to set 24 bit flag by default, people who use your app are translators mostly and as I proved to you Dolby media Encoder encodes 24 bit Atmos THD even better than 16 bit, which is a known design bug. And of course ADM is 24 bytes by default.

**Comment by ValZapod** [comment] 2023-01-26 12:25
We already disscused it https://github.com/VoidXH/Cavern/issues/8

What changed? Yes, the difference is minimal but it is there. You need 24 bit for editing.

>the user wants to use the result in another project,

That is the main use case, editing Atmos.

**Comment by VoidXH** [comment] 2023-01-26 12:55
> You need 24 bit for editing.

Yes, for editing only, but this only applies to less than 0.01% of users. As far as I know most ADM users use it for JOC playback on studio systems.
