### ISSUE TITLE
Protect Cavernize virtualization from clipping

### ISSUE THREAD

**Issue by kaedewang** [VoidXH/Cavern#88] opened 2023-02-17 03:40 UTC
content: dolby amaze
render target: headphone
issue: heavy clip when rain and thunder
![图片](https://user-images.githubusercontent.com/67850015/219543625-46b7e674-0f31-4e4e-8db1-0722b6515e48.png)

**Comment by VoidXH** [comment] 2023-02-17 18:53
Fixed in 474f6cacb152f9cdbf738700d222aedf560592e0.

**Closed by VoidXH** 2023-02-17 18:53 UTC
Labels: bug

**Comment by kaedewang** [comment] 2023-02-18 03:17
From 45s, some peoples report rain is not nature, rain jumps from one speaker to another suddenly in 7.1.4 and headphone, I hear some pops.

**Comment by VoidXH** [comment] 2023-02-18 11:03
Yes, that content is sometimes switching to vector encoding, which can't be decoded, because of #17. The standard is incorrectly written.

**Comment by kaedewang** [comment] 2023-02-25 01:17
I am interested in dolby atmos standard，could you please teach me where I can get?

**Comment by VoidXH** [comment] 2023-02-25 11:06
ETSI 103 420

**Comment by ValZapod** [comment] 2023-03-02 08:50
>ETSI 103 420

And many others, like
ETSI TS 102 366 V1.4.1  here are ETSI insider master documents (.docx that is, from which pdf is Adobe "printed") [sttandard.zip](https://github.com/VoidXH/Cavern/files/10869310/sttandard.zip)

**Comment by kaedewang** [comment] 2023-03-15 03:22
Thank you. I am reading slowly at work.
And
content: dolby amaze
render target: 5.1.2front
issue: heavy clip when rain and thunder
too.

**Comment by VoidXH** [comment] 2023-03-15 12:24
That is caused by #17 and is currently unfixable.

**Comment by kaedewang** [comment] 2023-03-16 02:10
Sparse is only found in some versions of amaze. Now other movies have no problem.
Am I right?
But 7.1.4 of amaze has no clip. Why?

**Comment by VoidXH** [comment] 2023-03-16 10:29
> Sparse is only found in some versions of amaze.

Sparse is always in the 7.1 sources for some reason. The 5.1 version of Amaze works perfectly.
