### ISSUE TITLE
Support ASIO

### ISSUE THREAD

**Issue by ChestZ** [VoidXH/Cavern#12] opened 2022-09-15 20:57 UTC
Is it possible to add support for ASIO drivers?
This would allow to support the 7.1.4 format.
Thanks

**Comment by ValZapod** [comment] 2022-09-16 09:08
That is for outputing to atmos renderer in Nuendo, the only app that inlcudes Atmos out of the box? You need to get 512 samples for it first using special ASIO called ASIo4ALL v2...

**Comment by VoidXH** [comment] 2022-09-16 09:14
Since Cavern creates audio files, this is the job of the player you use. Cavern will have a player in the far future, but not until the decoder is finalized.

**Comment by ValZapod** [comment] 2022-09-16 09:16
> this is the job of the player you use

It may be that Nuendo does not like that you file is not tagged ADM profile: Dilby Atmos Master, Version 1

**Comment by VoidXH** [comment] 2022-09-16 09:23
User reports say it works without issues. The caller asked for ASIO system output, but this software is just a converter, not a player.

**Comment by VoidXH** [comment] 2022-09-18 16:14
Closing as Nuendo import reported working.

**Closed by VoidXH** 2022-09-18 16:14 UTC

**Comment by ValZapod** [comment] 2022-10-02 19:11
BTW, since Dolby Media Encoder leaked I can confirm it does not like Atmos ADM. It does not consider it as Atmos. You need to somehow write ADM profile: Dolby Atmos Master, Version 1.

See this sample as to how this profile is written (it works with Media Encoder, no problem, atmos in AC3, EAC3, TrueHD). https://dolby.app.box.com/s/bart3gfwblydjysegkltoz08wqlvzspg

From here: https://learning.dolby.com/hc/en-us/articles/360054955591-Exercise-2-ADM-BWF-Import-to-Pro-Tools-and-Renderer-Monitoring-Operations

**Comment by VoidXH** [comment] 2022-10-07 17:33
Moved @ValZapod's request to #25.
